def menu():
          print("="*60)
          print("\t\t BANK OPERATION ")
          print("="*60)
          print("\t\t1. WithDarw ")
          print("\t\t2. Deposite ")
          print("\t\t3. Balance Enquiry ")
          print("\t\t4. Change Mobile Number")
          print("\t\t5. Fund Transfer to another A/C")
          print("\t\t6. Close Bank A/C")
          print("\t\t7. Exit ")
          print("="*60)
